name: Build and Push Docker image

on:
  push:
    branches:
      - main
      - GetQuery
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: ls -alh

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: prabhutejad/jsswnodejsapi:latest

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job runs only after the build job succeeds
    
    steps:
      
    - name: Trigger Render Deploy
      run: curl -X POST "${{ secrets.TriggerRender }}"
