name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install


      - name: Google Cloud CLI Setup
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          service_key: ${{ secrets.GCP_SA_KEY }}
          project_id: dyanamicwebsites  # Replace with your Google Cloud project ID

      - name: Deploy to Google App Engine
        run: gcloud app deploy --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
