name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: ls -alh

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: dyanamicwebsites

    - name: Log in to Google Cloud
      run: gcloud auth configure-docker

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: gcr.io/dyanamicwebsites/test:latest

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: build 
    
    steps:
    - name: Trigger Render Deploy
      run: curl -X POST "${{ secrets.TriggerRender }}"
